version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: personal-finance_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=personal_finance
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: personal-finance_redis
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - redis-data:/data

  pgadmin4:
    container_name: personal-finance_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_logs:/var/log/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis-data:
  pgadmin_data:
  pgadmin_logs:
