// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSchema_migrations = "schema_migrations"

// Schema_migrations mapped from table <schema_migrations>
type Schema_migrations struct {
	Version int64 `gorm:"column:version;primaryKey" json:"version"`
	Dirty   bool  `gorm:"column:dirty;not null" json:"dirty"`
}

// TableName Schema_migrations's table name
func (*Schema_migrations) TableName() string {
	return TableNameSchema_migrations
}
