// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsers = "users"

// Users mapped from table <users>
type Users struct {
	UserID         string    `gorm:"column:user_id;primaryKey" json:"user_id"`
	Email          string    `gorm:"column:email;not null" json:"email"`
	HashedPassword string    `gorm:"column:hashed_password;not null" json:"hashed_password"`
	FirstName      string    `gorm:"column:first_name;not null" json:"first_name"`
	MiddleName     string    `gorm:"column:middle_name" json:"middle_name"`
	LastName       string    `gorm:"column:last_name;not null" json:"last_name"`
	ProfilePicture string    `gorm:"column:profile_picture" json:"profile_picture"`
	PhoneNumber    string    `gorm:"column:phone_number" json:"phone_number"`
	Currency       string    `gorm:"column:currency;not null" json:"currency"`
	IsVerified     bool      `gorm:"column:is_verified;not null" json:"is_verified"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Users's table name
func (*Users) TableName() string {
	return TableNameUsers
}
